In [1]:
import pandas as pd
import numpy as np
%matplotlib inline

In [15]:
pwd

'/Users/ssadalgekar/Desktop/chicago-ds-080519/Module 1/dsc-module-1-assessment'

In [16]:
df = pd.read_csv('fifa.csv')
df.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,226500.0
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,127100.0
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,228100.0
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,138600.0
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,196400.0

In [17]:
df.drop(columns = ['Unnamed: 0'],inplace=True)

In [34]:
df.shape

(18207, 88)

In [5]:
# df.dropna(subset=['Release Clause'],inplace=True)

In [11]:
#df.dropna(subset=['Wage']).shape

(18207, 88)

In [18]:
df.shape

(20000, 88)

In [19]:
def convert_money(m):
    try:
        if m == 'None':
            return m
        else:
            m = m[1:]
            if m[-1] == 'K':
                m = float(m[:-1])*1000
            elif m[-1] == 'M':
                m = float(m[:-1])*1000
            return int(m)
    except:
        return float("Nan")

In [37]:
df['Release Clause'] = df['Release Clause'].apply(lambda x: convert_money(x))

In [14]:
# df['Wage'] = df['Wage'].apply(lambda x: convert_money(x))

In [20]:
print(df.shape)
print(df.dropna(subset=['Release Clause']).shape)

(20000, 88)
(18273, 88)

In [21]:
df.describe()

,ID,Age,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,Jersey Number,Crossing,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
count,20000.000000,20000.00000,20000.00000,20000.000000,20000.000000,19952.000000,19952.000000,19952.000000,19939.000000,19952.000000,...,19952.000000,19952.000000,19952.000000,19952.000000,19952.000000,19952.000000,19952.000000,19952.000000,19952.000000,18273.000000
mean,214056.958950,25.19545,66.24150,71.208150,1599.703850,1.103498,2.948025,2.365076,19.385726,49.869236,...,58.685696,47.422063,47.806736,45.757117,16.513984,16.285184,16.131165,16.294457,16.600491,231391.862146
std,29835.144399,4.64711,6.59385,6.010926,267.341782,0.377774,0.659637,0.749276,15.846335,18.182066,...,11.138706,19.757021,21.521219,21.160479,17.550120,16.777458,16.376668,16.912982,17.820566,305836.410351
min,16.000000,16.00000,46.00000,48.000000,731.000000,1.000000,1.000000,1.000000,1.000000,5.000000,...,3.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1000.000000
25%,200277.250000,21.00000,62.00000,67.000000,1466.000000,1.000000,3.000000,2.000000,8.000000,38.000000,...,52.000000,30.000000,27.000000,24.000000,8.000000,8.000000,8.000000,8.000000,8.000000,2100.000000
50%,221481.500000,25.00000,66.00000,71.000000,1641.000000,1.000000,3.000000,2.000000,17.000000,54.000000,...,60.000000,53.000000,55.000000,52.000000,11.000000,11.000000,11.000000,11.000000,11.000000,17300.000000
75%,236037.250000,28.00000,70.00000,75.000000,1781.000000,1.000000,3.000000,3.000000,26.000000,64.000000,...,66.000000,64.000000,66.000000,64.000000,14.000000,14.000000,14.000000,14.000000,14.000000,439000.000000
max,246620.000000,45.00000,94.00000,95.000000,2346.000000,5.000000,5.000000,5.000000,99.000000,93.000000,...,96.000000,94.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000,999000.000000

In [22]:
df.iloc[0:10000].to_csv('data/fifa_19_part_one.csv',index=False)
df.iloc[-10000:].to_csv('data/fifa_19_part_two.csv',index=False)

In [23]:
df.columns

Index(['ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall',
       'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes', 'Release Clause'],
      dtype='object')

In [48]:
df.shape

(20000, 88)